### ISSUE TITLE
Create button for navigation

### ISSUE THREAD

**Issue by RikaAJN** [TE-Flutter/Risehallrepo#11]
On the screen for the create, I want to create a button for navigation

**Comment by Infamous-johnnytech** [comment]
You can use 'flatbutton' or raisedbutton' widget to create a button in flutter.
check out this flutter documentation : 

https://api.flutter.dev/flutter/material/FlatButton-class.html
https://api.flutter.dev/flutter/material/RaisedButton-class.html
