### ISSUE TITLE
Add Search button and content 

### ISSUE THREAD

**Issue by RikaAJN** [TE-Flutter/Risehallrepo#34]
Screen to display contents for search

**Comment by khlebobul** [comment]
I don't quite understand the task, but there is an example of a search

https://user-images.githubusercontent.com/77191581/203555527-bad838fd-772b-4a6e-a051-64dd0699cb5b.mov

You can find code in DartPad Sample ["GoRouter sample"](https://dartpad.dev/?id=4a546fc44db8aca351bfe791e251acc2)

**Comment by khlebobul** [comment]
I don't quite understand the task, but there is an example of a search. You cam find code in [DartPad Sample](https://dartpad.dev/?id=4a546fc44db8aca351bfe791e251acc2) 


https://user-images.githubusercontent.com/77191581/203556329-4b5e2337-e785-4fa9-ad9c-550dae0e007f.mov
