### ISSUE TITLE
Create a page to collect User information 

### ISSUE THREAD

**Issue by RikaAJN** [TE-Flutter/Risehallrepo#5]
Code to create a page which displays buttons, placeholder text and drop downs for users to select

**Comment by Infamous-johnnytech** [comment]
You can use the Email and Password form we did in class, here is a flutter documentation for the "form" widget

https://api.flutter.dev/flutter/widgets/Form-class.html


or you could check this code, 
Form(
  key: _formKey,
  child: Column(
    children: [
      TextFormField(
        decoration: InputDecoration(labelText: 'Enter your email'),
        validator: (value) {
          if (value.isEmpty) {
            return 'Please enter your email';
          }
          return null;
        },
      ),
      TextFormField(
        decoration: InputDecoration(labelText: 'Enter your password'),
        validator: (value) {
          if (value.isEmpty) {
            return 'Please enter your password';
          }
          return null;
        },
      ),
      RaisedButton(
        onPressed: () {
          // Validate returns true if the form is valid, otherwise false.
          if (_formKey.currentState.validate()) {
            // If the form is valid, display a Snackbar.
            Scaffold.of(context).showSnackBar(
              SnackBar(content: Text('Processing Data')),
            );
          }
        },
        child: Text('Submit'),
      ),
    ],
  ),
)
